from pptx import Presentation
from pptx.util import Inches
import os
import logging

logger = logging.getLogger(__name__)

def create_powerpoint_slides(event_summary):
    """Create a PowerPoint presentation with basic slides."""
    try:
        # Create a new presentation
        prs = Presentation()

        # Slide 1: Title Slide
        slide_layout = prs.slide_layouts[0]  # Title Slide layout
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = f"Presentation for {event_summary}"
        subtitle.text = "Generated by PIN AI"

        # Slide 2: Content Slide
        slide_layout = prs.slide_layouts[1]  # Title and Content layout
        slide = prs.slides.add_slide(slide_layout)
        title = slide.shapes.title
        body = slide.placeholders[1]
        title.text = "Agenda"
        body.text = "1. Introduction\n2. Key Points\n3. Discussion\n4. Next Steps"

        # Save the presentation
        output_dir = "presentations"
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, f"slides_{event_summary.replace(' ', '_')}.pptx")
        prs.save(output_path)
        logger.info(f"Created PowerPoint presentation: {output_path}")
        return {"action": "Created slides", "details": {"file_path": output_path}}
    except Exception as e:
        logger.error(f"Error creating PowerPoint slides: {e}")
        raise